### PR TITLE
update hamming

### PR DESCRIPTION
**Pull request by zarniak**
checked with pep8
check couple of unittests
@virtuallight - you think it could be shorter?

### CODE REVIEW

**Comment by virtuallight** [comment]
@zarniak In Python - it can almost always be done shorter :P But if more readable - that's not that straightforward most of the times.

An example of a 1-liner for this: 
```
def hamming_distance(s1, s2):
    return sum(char_1 != char_2 for char_1, char_2 in zip(s1,s2))
```

The tests check for one extra thing though: https://github.com/zarniak/exercism.io/blob/master/hamming_test.py#L49 and https://github.com/zarniak/exercism.io/blob/master/hamming_test.py#L53 - both input strings have to be of same length. If they aren't, a `ValueError` should be raised. Python docs are unfortunately rather short of explanation here: https://docs.python.org/3/library/exceptions.html#ValueError. The easiest way to fullfill this requirement would be to check if the strings are equal and if not - `raise ValueError`. `raise` stops the execution of the code so no extra `return` is required.

**Comment by zarniak** [comment]
@virtuallight why getiing errors when adding raise ValueError

def distance(strand_a, strand_b):
    if len(strand_a) != len(strand_b):
        raise ValueError('a')
    else:
        return sum(char_1 != char_2 for char_1, char_2 in zip(strand_a, strand_b))

print(distance("ACAGGG", "ACTATGG"))

the result is

Traceback (most recent call last):                                                                                                                          
  File "/home/main.py", line 7, in <module>                                                                                                                 
    print(distance("ACAGGG", "ACTATGG"))                                                                                                                    
  File "/home/main.py", line 3, in distance                                                                                                                 
    raise ValueError('a')                                                                                                                                   
ValueError: a

**Comment by virtuallight** [comment]
> @virtuallight why getiing errors when adding raise ValueError
> 
> def distance(strand_a, strand_b):
> if len(strand_a) != len(strand_b):
> raise ValueError('a')
> else:
> return sum(char_1 != char_2 for char_1, char_2 in zip(strand_a, strand_b))
> 
> print(distance("ACAGGG", "ACTATGG"))
> 
> the result is
> 
> Traceback (most recent call last):
> File "/home/main.py", line 7, in 
> print(distance("ACAGGG", "ACTATGG"))
> File "/home/main.py", line 3, in distance
> raise ValueError('a')
> ValueError: a

@zarniak Would you mind making the snippet you've provided a bit more readable? GitHug ships with it's markup language https://guides.github.com/features/mastering-markdown/ and you can style a block of code with it.

**Comment by zarniak** [comment]
@virtuallight this way is more readable?
```
def distance(strand_a, strand_b):
if len(strand_a) != len(strand_b):
raise ValueError('a')
else:
return sum(char_1 != char_2 for char_1, char_2 in zip(strand_a, strand_b))

print(distance("ACAGGG", "ACTATGG"))
```

the result is

```
Traceback (most recent call last):
File "/home/main.py", line 7, in
print(distance("ACAGGG", "ACTATGG"))
File "/home/main.py", line 3, in distance
raise ValueError('a')
ValueError: a
```

**Comment by virtuallight** [comment]
@zarniak 👀Better! Thanks! 

Alos, you might also want to keep the indentation, so:
```
def distance(strand_a, strand_b):
    if len(strand_a) != len(strand_b):
        raise ValueError('a')
    else:
        return sum(char_1 != char_2 for char_1, char_2 in zip(strand_a, strand_b))

print(distance("ACAGGG", "ACTATGG"))
```

Ok. So the behavior you've got (`ValueError: a`) is expected. That `raise ValueError('a')` raises that error. And according to the tests that it what your code should do: 
- https://github.com/zarniak/exercism.io/blob/master/hamming_test.py#L49
- https://github.com/zarniak/exercism.io/blob/master/hamming_test.py#L53
Those are 2 cases where the input strings are of different length. In that case, your code should raise a ValueError, as in the example you've attached to the code `distance("ACAGGG", "ACTATGG")` where `ACAGGG` has 6 characters and `ACTATGG` has 7 characters.

Try removing that line `print(distance("ACAGGG", "ACTATGG"))` and run the rest of the code against the tests. That looks like it should work!

**Comment by zarniak** [comment]
@virtuallight it is working without print command - tests are ok :)

**Pull request merged**
